import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';

const configured = SUPABASE_URL.startsWith('https://') && !SUPABASE_PUBLISHABLE_KEY.startsWith('YOUR_');
const supabase = configured ? createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY) : null;
const initialDecks = [
  { id: 'travel', name: '여행 스페인어', icon: '✈️', words: [
    { front: 'hola', back: '안녕', example: '¡Hola! ¿Cómo estás?' },
    { front: 'gracias', back: '고마워', example: 'Muchas gracias.' },
    { front: 'por favor', back: '부탁합니다', example: 'Un café, por favor.' },
    { front: '¿dónde está...?', back: '…은 어디에 있나요?', example: '¿Dónde está el baño?' },
    { front: 'la cuenta', back: '계산서', example: 'La cuenta, por favor.' }
  ]},
  { id: 'daily', name: '기초 일상회화', icon: '☀️', words: [
    { front: 'amigo', back: '친구', example: 'Él es mi amigo.' },
    { front: 'familia', back: '가족', example: 'Mi familia es grande.' },
    { front: 'comer', back: '먹다', example: 'Quiero comer.' },
    { front: 'hoy', back: '오늘', example: 'Hoy es lunes.' }
  ]}
];

const state = {
  screen: 'home', drawer: false, language: '스페인어', deckId: 'travel', cardIndex: 0,
  revealed: false, shuffle: false, quizType: 'choice', quizIndex: 0, mistakes: [],
  dark: localStorage.getItem('lingo-dark') === 'true', modal: null, selectedDeck: null,
  user: null, authMode: 'login', loading: false, ocrPairs: []
};
let decks = [];

const $ = (s) => document.querySelector(s);
const save = () => {};
const deck = () => decks.find(d => d.id === state.deckId) || decks[0];
const escape = (text) => String(text).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function icon(name) { return `<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#${name}" /></svg>`; }

function render() {
  document.body.classList.toggle('dark', state.dark);
  $('#app').innerHTML = `${symbols()}<main class="shell">${header()}${content()}${nav()}</main>${drawer()}${modal()}`;
  bind();
}
function symbols() { return `<svg class="symbols" xmlns="http://www.w3.org/2000/svg"><symbol id="menu" viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></symbol><symbol id="home" viewBox="0 0 24 24"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V10Z"/><path d="M9 21v-6h6v6"/></symbol><symbol id="book" viewBox="0 0 24 24"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v17H6.5A2.5 2.5 0 0 0 4 22V5.5Z"/><path d="M4 18.5A2.5 2.5 0 0 1 6.5 16H20"/></symbol><symbol id="plus" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></symbol><symbol id="chev" viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></symbol><symbol id="shuffle" viewBox="0 0 24 24"><path d="m16 3 4 4-4 4M4 7h3c4 0 5 10 10 10h3M20 17l-4 4M4 17h3c1.8 0 3-2 4.2-4"/></symbol><symbol id="sun" viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></symbol><symbol id="user" viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21c.8-4 3.5-6 8-6s7.2 2 8 6"/></symbol><symbol id="settings" viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.2 2.2-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.5v.2h-3.2v-.2a1.7 1.7 0 0 0-1-1.5 1.7 1.7 0 0 0-1.9.3l-.1.1-2.2-2.2.1-.1a1.7 1.7 0 0 0 .3-1.9 1.7 1.7 0 0 0-1.5-1H5v-3.2h.2a1.7 1.7 0 0 0 1.5-1 1.7 1.7 0 0 0-.3-1.9l-.1-.1 2.2-2.2.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.5V3.5h3.2v.2a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.9-.3l.1-.1 2.2 2.2-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.5 1h.2V13h-.2a1.7 1.7 0 0 0-1.5 2Z"/></symbol></svg>`; }
function header() { const title = !state.user ? 'Lingo에 오신 걸 환영해요' : state.screen === 'home' ? `안녕하세요, ${state.user.email.split('@')[0]}님` : state.screen === 'study' ? deck().name : state.screen === 'quiz' ? '퀴즈' : state.screen === 'mistakes' ? '오답 노트' : '새 단어장'; return `<header><div><p class="eyebrow">${!state.user ? '나만의 언어 학습 공간' : state.screen === 'home' ? '오늘도 한 걸음씩' : state.language}</p><h1>${title}</h1></div>${state.user?`<button class="icon-btn" data-action="drawer">${icon('menu')}</button>`:''}</header>`; }
function content() { return `<section class="content">${!configured ? setup() : !state.user ? auth() : state.screen === 'home' ? home() : state.screen === 'study' ? study() : state.screen === 'quiz' ? quiz() : state.screen === 'mistakes' ? mistakes() : create()}</section>`; }
function setup(){return `<div class="empty"><div>⚙</div><h2>서버 연결을 준비해 주세요</h2><p>config.js에 Supabase 주소와 Publishable key를 넣으면 회원가입과 클라우드 저장을 시작할 수 있어요.</p></div>`}
function auth(){return `<div class="auth-card"><div class="auth-mark">L</div><h2>${state.authMode==='login'?'로그인':'회원가입'}</h2><p>${state.authMode==='login'?'어디서든 내 단어장을 이어서 학습하세요.':'가입하면 단어장이 개인 계정에 안전하게 저장돼요.'}</p><form id="auth-form"><label>이메일<input type="email" name="email" required autocomplete="email" placeholder="name@example.com" /></label><label>비밀번호<input type="password" name="password" required minlength="8" autocomplete="current-password" placeholder="8자 이상" /></label><button class="primary" type="submit">${state.authMode==='login'?'로그인':'회원가입'}</button></form><button class="auth-switch" data-action="auth-mode">${state.authMode==='login'?'계정이 없나요? 회원가입':'이미 계정이 있나요? 로그인'}</button></div>`}
function languagePill(){return `<button class="language-pill" data-action="language">🇪🇸 ${state.language} ${icon('chev')}</button>`;}
function home() { const d=deck(); return `${languagePill()}<section class="hero"><div><span>LAST STUDIED</span><h2>${d.name}</h2><p>${d.words.length}개의 단어 · 오늘 0개 학습</p><button class="primary" data-screen="study">이어서 학습하기 ${icon('chev')}</button></div><div class="hero-art">¡Hola!<small>✦</small></div></section><div class="section-title"><h2>내 단어장</h2><button data-screen="create">+ 만들기</button></div><div class="deck-list">${decks.map(d=>`<button class="deck-row" data-deck="${d.id}"><span class="deck-icon">${d.icon}</span><span><b>${escape(d.name)}</b><small>${d.words.length}개의 단어</small></span>${icon('chev')}</button>`).join('')}</div><div class="section-title"><h2>학습 도구</h2></div><div class="tools"><button data-screen="quiz"><span>✎</span><b>퀴즈 풀기</b><small>기억을 확인해요</small></button><button data-screen="mistakes"><span>◉</span><b>오답 노트</b><small>${state.mistakes.length}개 복습 대기</small></button></div>`; }
function study() { const d=deck(), words = state.shuffle ? [...d.words].sort((a,b)=>a.front.localeCompare(b.front)) : d.words, word=words[state.cardIndex % words.length]; return `${languagePill()}<div class="study-meta"><span>${state.cardIndex % words.length + 1} / ${words.length}</span><button class="toggle ${state.shuffle?'on':''}" data-action="shuffle">${icon('shuffle')} 셔플</button></div><div class="progress"><i style="width:${((state.cardIndex%words.length+1)/words.length)*100}%"></i></div><button class="flashcard ${state.revealed?'revealed':''}" data-action="reveal"><span class="card-label">${state.revealed?'뜻':'스페인어'}</span><strong>${state.revealed?word.back:word.front}</strong><em>${state.revealed?word.example:'카드를 눌러 뜻 확인하기'}</em><small>${state.revealed?'다시 눌러 단어 보기':'탭해서 뒤집기'}</small></button><div class="answer-row"><button class="soft danger" data-action="next">아직 어려워요</button><button class="primary" data-action="next">알겠어요 ${icon('chev')}</button></div><p class="hint">학습 결과는 곧 복습 알림과 오답 노트에 반영돼요.</p>`; }
function quiz() { const d=deck(), word=d.words[state.quizIndex % d.words.length], options=[word.back,...d.words.filter(x=>x.back!==word.back).sort(()=>.5-Math.random()).slice(0,3).map(x=>x.back)].sort(()=>.5-Math.random()); const voice=state.quizType==='voice'; return `${languagePill()}<div class="quiz-types"><button class="${state.quizType==='choice'?'active':''}" data-quiz="choice">객관식</button><button class="${state.quizType==='spell'?'active':''}" data-quiz="spell">직접 입력</button><button class="${voice?'active':''}" data-quiz="voice">말하기</button></div><div class="quiz-card"><span class="card-label">${voice?'다음 뜻을 스페인어로 말해 보세요':'다음 스페인어의 뜻은?'}</span><strong>${voice?word.back:word.front}</strong>${state.quizType==='choice'?`<div class="choices">${options.map(o=>`<button data-answer="${escape(o)}">${escape(o)}</button>`).join('')}</div>`:voice?`<button class="voice-btn" data-action="voice">🎙 말하기 시작</button><p id="voice-result" class="hint">마이크 권한을 허용해 주세요.</p>`:`<form id="spell-form"><input autocomplete="off" placeholder="한국어 뜻을 입력하세요" /><button class="primary">확인</button></form>`}</div><p class="hint">정답: ${voice?word.front:word.back} · 틀린 문제는 오답 노트에 저장됩니다.</p>`; }
function mistakes(){ return `${languagePill()}<p class="intro">틀린 단어를 모아 다시 익혀 보세요.</p>${state.mistakes.length?`<div class="deck-list">${state.mistakes.map(w=>`<div class="mistake"><span>🇪🇸</span><div><b>${w.front}</b><small>${w.back}</small></div><button data-action="remove-mistake" data-word="${w.id}">완료</button></div>`).join('')}</div>`:`<div class="empty"><div>✓</div><h2>아직 오답이 없어요</h2><p>퀴즈에서 틀린 단어가 이곳에 쌓입니다.</p><button class="primary" data-screen="quiz">퀴즈 시작하기</button></div>`; }
function create(){return `${languagePill()}<div class="create-head"><h2>새 단어장을 만들어 볼까요?</h2><p>직접 입력하거나 사진에서 단어를 찾아볼 수 있어요.</p></div><form id="create-form" class="create-form"><label>단어장 이름<input name="name" required placeholder="예: DELE A1" /></label><label>스페인어 단어<input name="front" required placeholder="예: aprender" /></label><label>한국어 뜻<input name="back" required placeholder="예: 배우다" /></label><label>예문 <small>(선택)</small><input name="example" placeholder="예: Quiero aprender español." /></label><button class="primary" type="submit">단어장에 추가하기</button></form><div class="ocr-box"><b>📷 사진에서 단어 추출</b><p>사진 속에서 “스페인어 - 한국어” 형식의 줄을 읽어 첫 항목을 채웁니다. 내용을 확인한 뒤 저장하세요.</p><input id="image-input" type="file" accept="image/*" capture="environment" /><button class="soft" data-action="ocr">사진에서 읽기</button></div>`;}
function nav(){return state.user?`<nav><button class="${state.screen==='home'?'active':''}" data-screen="home">${icon('home')}<span>홈</span></button><button class="${state.screen==='study'?'active':''}" data-screen="study">${icon('book')}<span>단어장</span></button><button class="add" data-screen="create">${icon('plus')}</button><button class="${state.screen==='quiz'?'active':''}" data-screen="quiz"><span class="quiz-nav">✎</span><span>퀴즈</span></button><button class="${state.screen==='mistakes'?'active':''}" data-screen="mistakes"><span class="quiz-nav">◉</span><span>오답</span></button></nav>`:'';}
function drawer(){return `<><div class="overlay ${state.drawer?'show':''}" data-action="drawer"></div><aside class="drawer ${state.drawer?'show':''}"><div class="brand"><div class="logo">L</div><b>Lingo</b><button data-action="drawer">×</button></div><div class="profile"><span>🌿</span><div><b>${escape(state.user?.email||'')}</b><small>클라우드 동기화 사용 중</small></div></div><div class="drawer-links"><button data-action="login">${icon('user')} 회원 정보 ${icon('chev')}</button><button class="disabled">◌ 언어 학습 모드 <small>준비 중</small></button><button data-screen="study" data-action="drawer">${icon('book')} 단어장 모드 ${icon('chev')}</button><button data-action="settings">${icon('settings')} 설정 ${icon('chev')}</button><button data-action="logout">${icon('user')} 로그아웃</button></div><p>v0.2 · 계정에 안전하게 동기화됨</p></aside></>`;}
function modal(){ if(!state.modal)return ''; const content=state.modal==='language'?`<h2>학습 언어</h2><button class="choice-line selected">🇪🇸 스페인어 <b>✓</b></button><button class="choice-line disabled">🇬🇧 영어 <small>준비 중</small></button><button class="choice-line disabled">🇨🇳 중국어 <small>준비 중</small></button>`:state.modal==='settings'?`<h2>설정</h2><button class="choice-line" data-action="dark">${icon('sun')} 다크 모드 <span class="switch ${state.dark?'on':''}"></span></button><button class="choice-line disabled">✉ 관리자 문의 <small>준비 중</small></button>`:`<h2>회원 정보</h2><p class="modal-copy">계정을 연결하면 여러 기기에서 단어장을 동기화하고 친구와 공유할 수 있어요.</p><button class="primary disabled">로그인 기능 준비 중</button>`;return `<div class="modal-wrap"><div class="modal-back" data-action="close-modal"></div><section class="modal"><button class="close" data-action="close-modal">×</button>${content}</section></div>`; }
function bind(){ document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.screen;state.revealed=false;state.cardIndex=0;state.drawer=false;render()}); document.querySelectorAll('[data-deck]').forEach(b=>b.onclick=()=>{state.deckId=b.dataset.deck;state.screen='study';state.cardIndex=0;render()}); document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b)); document.querySelectorAll('[data-quiz]').forEach(b=>b.onclick=()=>{state.quizType=b.dataset.quiz;render()}); document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer)); const form=$('#create-form');if(form)form.onsubmit=createDeck; const authForm=$('#auth-form');if(authForm)authForm.onsubmit=authenticate; const spell=$('#spell-form');if(spell)spell.onsubmit=e=>{e.preventDefault();answer(spell.querySelector('input').value.trim())}; }
async function action(a, el){if(el.dataset.screen){state.screen=el.dataset.screen;state.revealed=false;state.cardIndex=0}if(a==='drawer')state.drawer=!state.drawer;if(a==='language')state.modal='language';if(a==='settings')state.modal='settings';if(a==='login')state.modal='login';if(a==='close-modal')state.modal=null;if(a==='auth-mode'){state.authMode=state.authMode==='login'?'signup':'login'}if(a==='logout'){await supabase.auth.signOut();state.user=null;decks=[];state.drawer=false}if(a==='dark'){state.dark=!state.dark;localStorage.setItem('lingo-dark',state.dark)}if(a==='reveal')state.revealed=!state.revealed;if(a==='shuffle')state.shuffle=!state.shuffle;if(a==='next'){state.cardIndex++;state.revealed=false}if(a==='remove-mistake'){await supabase.from('mistakes').delete().eq('word_id',el.dataset.word);state.mistakes=state.mistakes.filter(w=>w.id!==el.dataset.word)}if(a==='voice'){listenForAnswer();return}if(a==='ocr'){await readImage();return}render();}
async function answer(value){const w=deck().words[state.quizIndex%deck().words.length], expected=state.quizType==='voice'?w.front:w.back;const correct=normalise(value)===normalise(expected);if(!correct&&!state.mistakes.some(x=>x.id===w.id)){state.mistakes.push(w);await supabase.from('mistakes').upsert({owner_id:state.user.id,word_id:w.id},{onConflict:'owner_id,word_id'})}alert(correct?'정답이에요! 🎉':'아쉬워요. 정답은 “'+expected+'”입니다.');state.quizIndex++;render();}
const normalise=v=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f\s.,!?¿¡]/g,'');
async function authenticate(e){e.preventDefault();const f=new FormData(e.target),email=f.get('email').trim(),password=f.get('password');const result=state.authMode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(result.error)return alert(result.error.message);if(!result.data.session&&state.authMode==='signup')return alert('가입 확인 메일을 보냈어요. 메일의 링크를 누른 뒤 로그인해 주세요.');state.user=result.data.user;await loadCloudData();render();}
async function loadCloudData(){const {data,error}=await supabase.from('decks').select('id,name,icon,language,words(id,front,back,example)').order('created_at');if(error)return alert('단어장을 불러오지 못했어요: '+error.message);decks=data||[];if(!decks.length){for(const sample of initialDecks){const {data:d}=await supabase.from('decks').insert({owner_id:state.user.id,name:sample.name,icon:sample.icon,language:'스페인어'}).select().single();await supabase.from('words').insert(sample.words.map(w=>({...w,deck_id:d.id})));}return loadCloudData()}state.deckId=decks[0].id;const {data:m}=await supabase.from('mistakes').select('word_id,words(id,front,back,example)').eq('owner_id',state.user.id);state.mistakes=(m||[]).map(x=>x.words).filter(Boolean);}
async function createDeck(e){e.preventDefault();const f=new FormData(e.target),name=f.get('name').trim(),front=f.get('front').trim(),back=f.get('back').trim(),example=f.get('example').trim();let d=decks.find(x=>x.name===name);if(!d){const r=await supabase.from('decks').insert({owner_id:state.user.id,name,icon:'📚',language:state.language}).select().single();if(r.error)return alert(r.error.message);d={...r.data,words:[]};decks.push(d)}const r=await supabase.from('words').insert({deck_id:d.id,front,back,example}).select().single();if(r.error)return alert(r.error.message);d.words.push(r.data);state.deckId=d.id;state.screen='study';state.cardIndex=d.words.length-1;render();}
async function readImage(){const input=$('#image-input');if(!input?.files?.[0])return alert('먼저 카메라나 갤러리에서 사진을 선택해 주세요.');const btn=document.querySelector('[data-action="ocr"]');btn.textContent='읽는 중…';try{const {createWorker}=await import('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.esm.min.js');const worker=await createWorker('spa+kor');const {data:{text}}=await worker.recognize(input.files[0]);await worker.terminate();const pair=text.split(/\r?\n/).map(line=>line.split(/\s*[-–—:=]\s*/)).find(x=>x.length===2);if(!pair)return alert('“스페인어 - 한국어”처럼 두 항목이 한 줄에 있는 사진을 사용해 주세요.');document.querySelector('[name="front"]').value=pair[0].trim();document.querySelector('[name="back"]').value=pair[1].trim()}catch(err){alert('사진 인식에 실패했어요: '+err.message)}finally{if(btn)btn.textContent='사진에서 읽기'}}
function listenForAnswer(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return alert('이 브라우저는 음성 인식을 지원하지 않아요. Safari 최신 버전 또는 Chrome에서 시도해 주세요.');const r=new Recognition();r.lang='es-ES';r.interimResults=false;r.onresult=e=>{const said=e.results[0][0].transcript;const result=$('#voice-result');if(result)result.textContent='인식한 답: '+said;answer(said)};r.onerror=()=>alert('음성을 인식하지 못했어요. 조용한 곳에서 다시 말해 주세요.');r.start();}
async function init(){if(!configured){render();return}const {data:{session}}=await supabase.auth.getSession();state.user=session?.user||null;if(state.user)await loadCloudData();supabase.auth.onAuthStateChange((_event,session)=>{state.user=session?.user||null});render()}
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
init();
